version: '3.8'

services:
    app:
        image: php:8.1-fpm
        container_name: appNews
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - laravel

    web:
        image: nginx:alpine
        container_name: webNews
        ports:
            - "8091:80"
        volumes:
            - ./:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:5.7
        container_name: dbNews
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
        environment:
            - discovery.type=single-node
        ports:
            - 9200:9200
        networks:
            - laraelastic
networks:
    laravel:
        driver: bridge

volumes:
    dbdata:
        driver: local
